on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["5.10.0", "6.14.16", "7.24.2", "8.6.0"]

    steps:
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc

      - run: npx npm@${{ matrix.version }} version

      - run: npx npm@${{ matrix.version }} ping --registry https://npm.pkg.github.com
